name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
            restore-keys: |
                ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
            python -m venv .televenv
            .\.televenv\Scripts\python.exe -m pip install --upgrade pip
            .\.televenv\Scripts\python.exe -m pip install -r requirements.txt

      - name: Download NLTK data
        run: |
            .\.televenv\Scripts\python.exe -m nltk.downloader stopwords wordnet punkt omw-1.4

      - name: Confirm Python version
        run: python --version

      - name: Run pytest
        run: .\.televenv\Scripts\python.exe -m pytest tests --maxfail=1 --disable-warnings -q